### ISSUE TITLE
{{ page.pdf_url }} does not print anything

### ISSUE THREAD

**Issue by sdarougheh** [jekyll-pdf/jekyll-pdf#6]
I added the gem to the Gemfile,  added
```

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      pdf: true
```
to the bottom of my _config.yml, seeing that defaults where not defined there anywhere (I'm working on a template that I didn't create myself).

I then went to my cv.md, and tried both {{ page.pdf_url }} and {{cv.pdf_url}} -- none of these would lead to any visible output in the published page, even after serving again.

What am I missing?
